safe: true
port: 4000
baseurl:    /
url: http://localhost:4000

source:      .
destination: ./_site
plugins_dir:     ./_plugins
plugins:
  - jekyll-redirect-from
future:      true
lsi:         false
highlighter:    null
markdown:    kramdown
permalink:   /:title/

exclude: [/coffeescript/,/localdev.sh]

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []
whitelist:
  - jekyll-redirect-from
kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  
  syntax_highlighter_opts:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style